### PR TITLE
Select groups and types

### PR DESCRIPTION
**Pull request by leelongmore**
Converts data source fields (group and type) on dashboard form into drop-down lists.

See https://www.agileplannerapp.com/boards/15088/cards/8879

Note - The querying of the data-sets endpoint (within the constructor DataSources class) was taking around 2-3 seconds in development. This is made worse by the data-sets endpoint being hit a second time when adding a new section or module into the form. A couple of options for improving performance have been explored but I suggest we wait to see how this aspect of the application performs in production before making changes.

### CODE REVIEW

**Comment by timmow** [comment]
Can we see how long it takes when deployed to preview - we can deploy this branch.

If its still 2 - 3 seconds, i'd be worried about deploying to production.

We could also feature flag this feature, so its easy to turn off it does cause issues.

I'd also like to put some statsd timers around it, so we can see exactly how long it takes.

**Comment by leelongmore** [comment]
I pushed the branch to Preview and asked Urmy to try it out. He was happy with it. Tim also tried it and it seemed to perform slower than for Urmy.

I've discussed with Matt H and he suggests we go-ahead and deploy.

**Comment by tombooth** [comment]
I second tim's ask for statsd timers around it, it would be good to have some data to look at.

**Comment by leelongmore** [comment]
A change has been made to Stagecraft to reduce the time taken to retrieve all data sets (see https://github.com/alphagov/stagecraft/pull/299). This has been merged.

**Pull request merged**
